all: hello convert_knots test_stack
hello: hello.cpp
	 g++ hello.cpp -o hello
convert_knots: convert_knots.cpp
	g++ convert_knots.cpp -o convert_knots 
test_stack: test_stack.cpp stack.h
	g++ test_stack.cpp -o test_stack

